# 查询分站信息
GET http://localhost:8202/admin/site/query?skip=0&limit=10 HTTP/1.1
Accept: application/json
X-Tenant: master

###
# 获取分站详情
GET http://localhost:8202/admin/site/fetch?site=99991 HTTP/1.1
Accept: application/json
X-Tenant: master

###
# 发布分站信息
POST http://localhost:8202/admin/site/create HTTP/1.1
Content-Type: application/json
X-Tenant: master
X-UserID: test
Accept: application/json

{
  "site": "99991",
  "name": "测试一校",
  "domain": "99991.smart.chinahuian.cn",
  "copyright": "吉林省高等学校毕业生就业指导中心 版权所有 | 域名备案信息：吉ICP备xxxxxxxx号",
  "content": "<p>就业网站演示系统</p>"
}

###
# 修改分站信息
POST http://localhost:8202/admin/site/update?site=99991 HTTP/1.1
Content-Type: application/json
X-Tenant: master
X-UserID: test
Accept: application/json

{
  "content": "<p>吉人生根工程”2019届吉林省普通高校毕业生专场招聘会<span style=\"color:red;\">福瑞科技</span></p>"
}

###
# 删除分站信息
POST http://localhost:8202/admin/site/delete?site=99991 HTTP/1.1
Content-Type: application/json
X-Tenant: master
X-UserID: test
Accept: application/json

{
  "content": "<p>吉人生根工程”2019届吉林省普通高校毕业生专场招聘会<span style=\"color:red;\">福瑞科技</span></p>"
}

###
# 获取分站配置
GET http://localhost:8202/admin/site/config HTTP/1.1
Accept: application/json
X-Tenant: 99991

###
# 设置分站配置
POST http://localhost:8202/admin/site/config HTTP/1.1
Content-Type: application/json
Accept: application/json
X-Tenant: 99991

{
  "content": "<p>分站联系方式：<span style=\"color:red;\">1234567890</span></p>"
}